### PR TITLE
fix: add processing to parse into serializable objects when sync mock object

### LINKED ISSUE #895: [🐛 Bug]: Cannot intercept call to electron.dialog.showOpenDialog when it is invoked with the browserWindow argument
Originally posted here: https://github.com/webdriverio/webdriverio/issues/14078

### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.40

### Node.js Version

20.11.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
    {
      browserName: "electron",
      // Electron service options
      // see https://webdriver.io/docs/desktop-testing/electron/configuration/#service-options
      "wdio:electronServiceOptions": {
        appBinaryPath: "path/to/my.exe"
        // custom application args
        appArgs: [],
      },
    },
  ],
```

### What happened?

In the electron app I have the following code:

```ts
const result = await dialog.showOpenDialog( {
    title: 'Select arxml',
    filters: [
      { name: 'ARXML', extensions: ['arxml'] },
      { name: 'All Files', extensions: ['*'] },
    ],
  });
```

In the test I mock calls to `showOpenDialog`:

```ts
const showOpenDialog : ElectronMock = await browser.electron.mock(
        "dialog",
        "showOpenDialog"
      );
```

If I change the code in the electron app to pass the browserWindow:

```ts
const result = await dialog.showOpenDialog(
    mainWindow,
    {
        title: 'Select arxml',
        filters: [
          { name: 'ARXML', extensions: ['arxml'] },
          { name: 'All Files', extensions: ['*'] },
        ],
    }
  });

The previous mock no longer reports any intercepted calls.

I verified that the changed application still works.

### What is your expected behavior?

To be able to intercept any form of `showOpenDialog`.

### How to reproduce the bug.

Use the code given above.

### Relevant log output

```typescript
There is a difference in the logs when adding the `window` parameter:


Error occurred in handler for 'wdio-electron.execute': Error: An object could not be cloned.
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78210)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by mato533**
### Description
Update the `mock.update` method to parse the object provided as a parameter into a serializable object when calling the mocked method.

In addition, we fixed the condition where mock.update is executed only when the `execute` command is executed, and changed it to target all commands(*) where the electron method may be called.

*) for now, i exclude the command `deleteSession`

Closes #895

### CODE REVIEW

File: packages/wdio-electron-service/src/service.ts [hunk 1]
```diff
@@ -143,7 +143,8 @@ export default class ElectronWorkerService implements Services.ServiceInstance {
     const mocks = mockStore.getMocks();
     const isInternalCommand = () => Boolean((args.at(-1) as ExecuteOpts)?.internal);
 
-    if (commandName === 'execute' && mocks.length > 0 && !isInternalCommand()) {
+    const excludeCommand = ['deleteSession'];
+    if (!excludeCommand.includes(commandName) && mocks.length > 0 && !isInternalCommand()) {
```
Comment (goosewobbler) [inline packages/wdio-electron-service/src/service.ts:147]: Just one question about this, we were updating the mocks after non-internal `execute` calls, now we are updating the mocks after all non-internal calls which aren't `deleteSession` - what's the reason for this and does it have a perf hit at all?

**Comment by goosewobbler** [comment]
Looks great, just the one question around the mock update change.

File: packages/wdio-electron-service/src/service.ts (hunk 1 above)
Comment (mato533) [reply packages/wdio-electron-service/src/service.ts:147]: I also wanted to discuss this point.

This is because to update all not internal command.

Changes have been made to address issues in the following use cases

- Premise
   Processing to call `showOpenDialog` has been implemented in electron app like below.
   https://github.com/webdriverio-community/wdio-electron-service/blob/2a9544598d48fcfbd31c895d354fbf4aac299b96/apps/builder-esm/src/main.ts#L51-L60

   *) In the above example, when the Button on the renderer side is pressed, the above method is called via IPC Bridge and `showOpenDialog` is executed.

- TestCase
   Suppose that the user wants to check whether `showOpenDialog` is actually called, or to test whether the processing performed using the result of the call is working correctly. The test case is as follows.
   https://github.com/webdriverio-community/wdio-electron-service/blob/2cf0475d9de129d138f546ce6ce97f86dab549e5/e2e/test/api.spec.ts#L786-L794
   
   *) The above example assumes that you want to check whether "showOpenDialog" was actually called.

- Issue
   This test case will fail without this implementation (condition change). This is because `execute` is never executed between `browser.$('.show-dialog').click();` where mock is called and `expect(***).toHaveBeenCalledTimes(1)`. As a result, `mock.update` is not executed and outerMock's calls is remained 0. 

- Resolution
  There might be other ways to do it, but here's what I came up with.
  - Update condition for execution of `mock.update` 
    I chose this option at PR. However, performance will be poor. But performance will be poor. CI is taking 1.5 to 2 times longer.
  - Update Docs to write that the user who want to execute this test case must call `mock.update` before `expected` is called.
    This approach may be better considering performance issues.

**Comment by mato533** [comment]
@goosewobbler 
Thank you for your review!! Sorry for the length, but I answered the questions I received.

File: packages/wdio-electron-service/src/service.ts (hunk 1 above)
Comment (goosewobbler) [reply packages/wdio-electron-service/src/service.ts:147]: Ok, I see.  Is there a further optimisation for the `mock.update` that we could use to improve the performance?  anything to reduce the number of calls really, without stopping the autoupdating from working.
Having to call `mock.update` for that specific case is kind of annoying, I think the first option is slightly better though that opinion might change depending on the size of app / amount of tests the user has integrated.
The third one sounds viable, however I'd rather not do loads of work on mocking before #308 is solved as the whole approach is likely to change as a result of that.

Comment (mato533) [reply packages/wdio-electron-service/src/service.ts:147]: @goosewobbler 
Thank you for understanding.
Basically I agree with your comment. I will consider about optimization. I just need a moment of your time.

**Comment by mato533** [comment]
|Element|[$$](https://webdriver.io/docs/api/element/$$)||
|Element|[$](https://webdriver.io/docs/api/element/$)||
|Element|[addValue](https://webdriver.io/docs/api/element/addValue)|YES|
|Element|[clearValue](https://webdriver.io/docs/api/element/clearValue)|YES|
|Element|[click](https://webdriver.io/docs/api/element/click)|YES|
|Element|[custom$$](https://webdriver.io/docs/api/element/custom$$)||
|Element|[custom$](https://webdriver.io/docs/api/element/custom$)||
|Element|[doubleClick](https://webdriver.io/docs/api/element/doubleClick)|YES|
|Element|[dragAndDrop](https://webdriver.io/docs/api/element/dragAndDrop)|YES|
|Element|[execute](https://webdriver.io/docs/api/element/execute)|YES|
|Element|[executeAsync](https://webdriver.io/docs/api/element/executeAsync)|YES|
|Element|[getAttribute](https://webdriver.io/docs/api/element/getAttribute)||
|Element|[getCSSProperty](https://webdriver.io/docs/api/element/getCSSProperty)||
|Element|[getComputedLabel](https://webdriver.io/docs/api/element/getComputedLabel)||
|Element|[getComputedRole](https://webdriver.io/docs/api/element/getComputedRole)||
|Element|[getElement](https://webdriver.io/docs/api/element/getElement)||
|Element|[getElements](https://webdriver.io/docs/api/element/getElements)||
|Element|[getHTML](https://webdriver.io/docs/api/element/getHTML)||
|Element|[getLocation](https://webdriver.io/docs/api/element/getLocation)||
|Element|[getProperty](https://webdriver.io/docs/api/element/getProperty)||
|Element|[getSize](https://webdriver.io/docs/api/element/getSize)||
|Element|[getTagName](https://webdriver.io/docs/api/element/getTagName)||
|Element|[getText](https://webdriver.io/docs/api/element/getText)||
|Element|[getValue](https://webdriver.io/docs/api/element/getValue)||
|Element|[isClickable](https://webdriver.io/docs/api/element/isClickable)||
|Element|[isDisplayed](https://webdriver.io/docs/api/element/isDisplayed)||
|Element|[isEnabled](https://webdriver.io/docs/api/element/isEnabled)||
|Element|[isEqual](https://webdriver.io/docs/api/element/isEqual)||
|Element|[isExisting](https://webdriver.io/docs/api/element/isExisting)||
|Element|[isFocused](https://webdriver.io/docs/api/element/isFocused)||
|Element|[isSelected](https://webdriver.io/docs/api/element/isSelected)||
|Element|[isStable](https://webdriver.io/docs/api/element/isStable)||
|Element|[moveTo](https://webdriver.io/docs/api/element/moveTo)|YES|
|Element|[nextElement](https://webdriver.io/docs/api/element/nextElement)||
|Element|[parentElement](https://webdriver.io/docs/api/element/parentElement)||
|Element|[previousElement](https://webdriver.io/docs/api/element/previousElement)||
|Element|[react$$](https://webdriver.io/docs/api/element/react$$)||
|Element|[react$](https://webdriver.io/docs/api/element/react$)||
|Element|[saveScreenshot](https://webdriver.io/docs/api/element/saveScreenshot)||
|Element|[scrollIntoView](https://webdriver.io/docs/api/element/scrollIntoView)|YES|
|Element|[selectByAttribute](https://webdriver.io/docs/api/element/selectByAttribute)|YES|
|Element|[selectByIndex](https://webdriver.io/docs/api/element/selectByIndex)|YES|
|Element|[selectByVisibleText](https://webdriver.io/docs/api/element/selectByVisibleText)|YES|
|Element|[setValue](https://webdriver.io/docs/api/element/setValue)|YES|
|Element|[shadow$$](https://webdriver.io/docs/api/element/shadow$$)||
|Element|[shadow$](https://webdriver.io/docs/api/element/shadow$)||
|Element|[touchAction](https://webdriver.io/docs/api/element/touchAction)|YES|
|Element|[waitForClickable](https://webdriver.io/docs/api/element/waitForClickable)||
|Element|[waitForDisplayed](https://webdriver.io/docs/api/element/waitForDisplayed)||
|Element|[waitForEnabled](https://webdriver.io/docs/api/element/waitForEnabled)||
|Element|[waitForExist](https://webdriver.io/docs/api/element/waitForExist)||
|Element|[waitForStable](https://webdriver.io/docs/api/element/waitForStable)||
|Element|[waitUntil](https://webdriver.io/docs/api/element/waitUntil)||

**Comment by mato533** [comment]
|Object|Command|InputCommand?|
|:----|:----|:----|
|browser|[$$](https://webdriver.io/docs/api/browser/$$)||
|browser|[$](https://webdriver.io/docs/api/browser/$)||
|browser|[action](https://webdriver.io/docs/api/browser/action)|YES|
|browser|[actions](https://webdriver.io/docs/api/browser/actions)|YES|
|browser|[addCommand](https://webdriver.io/docs/api/browser/addCommand)||
|browser|[addInitScript](https://webdriver.io/docs/api/browser/addInitScript)||
|browser|[call](https://webdriver.io/docs/api/browser/call)||
|browser|[custom$$](https://webdriver.io/docs/api/browser/custom$$)||
|browser|[custom$](https://webdriver.io/docs/api/browser/custom$)||
|browser|[debug](https://webdriver.io/docs/api/browser/debug)||
|browser|[deleteCookies](https://webdriver.io/docs/api/browser/deleteCookies)||
|browser|[downloadFile](https://webdriver.io/docs/api/browser/downloadFile)||
|browser|[emulate](https://webdriver.io/docs/api/browser/emulate)|YES|
|browser|[execute](https://webdriver.io/docs/api/browser/execute)|YES|
|browser|[executeAsync](https://webdriver.io/docs/api/browser/executeAsync)|YES|
|browser|[getCookies](https://webdriver.io/docs/api/browser/getCookies)||
|browser|[getPuppeteer](https://webdriver.io/docs/api/browser/getPuppeteer)||
|browser|[getWindowSize](https://webdriver.io/docs/api/browser/getWindowSize)||
|browser|[keys](https://webdriver.io/docs/api/browser/keys)|YES|
|browser|[mock](https://webdriver.io/docs/api/browser/mock)||
|browser|[mockClearAll](https://webdriver.io/docs/api/browser/mockClearAll)||
|browser|[mockRestoreAll](https://webdriver.io/docs/api/browser/mockRestoreAll)||
|browser|[newWindow](https://webdriver.io/docs/api/browser/newWindow)||
|browser|[overwriteCommand](https://webdriver.io/docs/api/browser/overwriteCommand)||
|browser|[pause](https://webdriver.io/docs/api/browser/pause)||
|browser|[react$$](https://webdriver.io/docs/api/browser/react$$)||
|browser|[react$](https://webdriver.io/docs/api/browser/react$)||
|browser|[reloadSession](https://webdriver.io/docs/api/browser/reloadSession)||
|browser|[restore](https://webdriver.io/docs/api/browser/restore)||
|browser|[savePDF](https://webdriver.io/docs/api/browser/savePDF)||
|browser|[saveRecordingScreen](https://webdriver.io/docs/api/browser/saveRecordingScreen)||
|browser|[saveScreenshot](https://webdriver.io/docs/api/browser/saveScreenshot)||
|browser|[scroll](https://webdriver.io/docs/api/browser/scroll)|YES|
|browser|[setCookies](https://webdriver.io/docs/api/browser/setCookies)||
|browser|[setTimeout](https://webdriver.io/docs/api/browser/setTimeout)||
|browser|[setViewport](https://webdriver.io/docs/api/browser/setViewport)||
|browser|[setWindowSize](https://webdriver.io/docs/api/browser/setWindowSize)|YES|
|browser|[switchFrame](https://webdriver.io/docs/api/browser/switchFrame)||
|browser|[switchWindow](https://webdriver.io/docs/api/browser/switchWindow)||
|browser|[throttle](https://webdriver.io/docs/api/browser/throttle)||
|browser|[throttleCPU](https://webdriver.io/docs/api/browser/throttleCPU)||
|browser|[throttleNetwork](https://webdriver.io/docs/api/browser/throttleNetwork)||
|browser|[touchAction](https://webdriver.io/docs/api/browser/touchAction)|YES|
|browser|[uploadFile](https://webdriver.io/docs/api/browser/uploadFile)|YES|
|browser|[url](https://webdriver.io/docs/api/browser/url)||
|browser|[waitUntil](https://webdriver.io/docs/api/browser/waitUntil)||

**Comment by goosewobbler** [comment]
I think having a whitelist of commands which trigger the mock update is a good idea, we can start with this input command list and go from there - I suspect just doing this will have a measurable perf gain.

**Comment by mato533** [comment]
@goosewobbler 
Thank you for your comment endorsement.
I have pushed some commit to this PR which is included the de-duplicated white-list is implemented by collecting commands for which the third column of the two tables is YES.
