### PR TITLE
fix: pass browserInstance through to `execute`

### LINKED ISSUE #313: Multiremote `execute` calls are returning an array of values for e.g. `app.getName()`
See https://github.com/webdriverio-community/wdio-electron-service/blob/cb/better-mock/example/multiremote/api.spec.ts

### PR DESCRIPTION
**Pull request by goosewobbler**
Fixes #313

### CODE REVIEW

File: src/service.ts [hunk 1]
```diff
@@ -21,10 +21,12 @@ export default class ElectronWorkerService implements Services.ServiceInstance {
...
   }
 
-  #getElectronAPI() {
+  #getElectronAPI(browserInstance?: WebdriverIO.Browser) {
+    const browser = (browserInstance || this.browser) as WebdriverIO.Browser;
     const api = {
       _mocks: {} as Record<string, ElectronServiceMock>,
-      execute: execute.bind(this),
+      execute: (script: string | ((...innerArgs: unknown[]) => unknown), ...args: unknown[]) =>
+        execute.apply(this, [browser, script, ...args]),
```
Comment (christian-bromann) [inline src/service.ts:29]: How about

```suggestion
        execute.apply(browser, [script, ...args]),
```

File: src/commands/execute.ts [hunk 2]
```diff
@@ -1,8 +1,7 @@
 import { CONTEXT_BRIDGE_NOT_AVAILABLE } from '../constants.js';
-import type ElectronWorkerService from '../service.js';
 
 export async function execute<ReturnValue, InnerArguments extends unknown[]>(
-  this: ElectronWorkerService,
+  browser: WebdriverIO.Browser,
```
Comment (christian-bromann) [inline src/commands/execute.ts:4]: and then do:
```suggestion
  this: WebdriverIO.Browser,
```

Comment (goosewobbler) [reply src/commands/execute.ts]: Tried these two - the instance test fails, producing an array of values again
